### ISSUE TITLE
Unable to install libspa-0.2-bluetooth

### ISSUE THREAD

**Issue by alsoGAMER** [pipewire-debian/pipewire-debian#4] opened 2021-05-03 17:55 UTC
**If you Completed all troubleshooting options, check below**
- [X]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting).

**Describe the bug**
Unable to install `libspa-0.2-bluetooth`

**To Reproduce**
Follow the second point of the installation guide (Install PipeWire)

**Expected behavior**
The package should install successfully

**Desktop (please complete the following information):**
 - Distro: Pop_OS
 - Desktop Environment: Gnome
 - Version: 20.04

**APT output and status of related services**
```Reading package lists... Done
Building dependency tree       
Reading state information... Done
gstreamer1.0-pipewire is already the newest version (0.3.26-3).
gstreamer1.0-pipewire set to manually installed.
libpipewire-0.3-0 is already the newest version (0.3.26-3).
libpipewire-0.3-0 set to manually installed.
libpipewire-0.3-modules is already the newest version (0.3.26-3).
libpipewire-0.3-modules set to manually installed.
libspa-0.2-modules is already the newest version (0.3.26-3).
libspa-0.2-modules set to manually installed.
pipewire is already the newest version (0.3.26-3).
pipewire-bin is already the newest version (0.3.26-3).
pipewire-bin set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libspa-0.2-bluetooth : Depends: libopenaptx0 (>= 0.2.0-5~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by souravdas142** [comment] 2021-05-03 18:16
try installing `libopenaptx0` first. then install `libspa-0.2-bluetooth`

if `libfdk-aac2` not found install `libfdk-aac1`

**Comment by alsoGAMER** [comment] 2021-05-04 07:08
> try installing `libopenaptx0` first. then install `libspa-0.2-bluetooth`

Same issue


> if `libfdk-aac2` not found install `libfdk-aac1`

This works fine, I've already installed `libfdk-aac2`

**Comment by pipewire-debian** [comment] 2021-05-04 08:13
The problem not reproducing for me, on a clean installed pop_os! 20.04.  attaching installation log [pop_os.log](https://pastebin.com/m8WmHTVr) . You can see by the end of this file, pipewire is working normally.

you can do, 
1. remove all packages related to PipeWire
2. sync your mirrors, with `sudo apt-get update` do that until there is no error.
2. Upgrade all system packages, with `sudo apt-get upgrade`
2. try to install `libopenaptx0` again. and give a full log.
3. if not working, remove if your distro has another version of `libopenaptx*` and  goto 1.

**Comment by alsoGAMER** [comment] 2021-05-04 14:58
> 1. remove all packages related to PipeWire

I can't remove any of the packages cause the removal will break my installation.
Here the APT output:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'libspa-0.2-bluetooth' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  fprintd gir1.2-accountsservice-1.0 gir1.2-gck-1 gir1.2-gcr-3 gir1.2-gdm-1.0 gir1.2-geoclue-2.0 gir1.2-gnomebluetooth-1.0 gir1.2-graphene-1.0 gir1.2-gweather-3.0 gir1.2-handy-0.0 gir1.2-json-1.0 gir1.2-nma-1.0 gir1.2-rsvg-2.0
  gir1.2-upowerglib-1.0 gjs gnome-session-bin gnome-session-common gnome-shell-common gnome-shell-extension-system76-power gnome-startup-applications gtk2-engines-murrine libfprint-2-2 libgjs0g libmozjs-78-0 libpam-fprintd libvncserver1
  mutter-common pop-gnome-shell-theme pop-gtk-theme pop-icon-theme pop-shell pop-shell-plugin-system76-power pop-shell-shortcuts pop-sound-theme pop-theme switcheroo-control xdg-desktop-portal xwayland
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  policykit-1-gnome
The following packages will be REMOVED:
  chrome-gnome-shell* gdm3* gir1.2-mutter-7* gnome-remote-desktop* gnome-shell* gnome-shell-extension-alt-tab-raise-first-window* gnome-shell-extension-always-show-workspaces* gnome-shell-extension-appindicator*
  gnome-shell-extension-desktop-icons-ng* gnome-shell-extension-pop-shop-details* gnome-shell-extension-prefs* gnome-tweaks* gstreamer1.0-pipewire* libmutter-7-0* libpipewire-0.3-0* libpipewire-0.3-dev* libpipewire-0.3-modules*
  libspa-0.2-dev* libspa-0.2-jack* libspa-0.2-modules* pipewire* pipewire-audio-client-libraries* pipewire-bin* pipewire-locales* pipewire-tests* pop-default-settings* pop-desktop* pop-session*
The following NEW packages will be installed:
  policykit-1-gnome
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  pop-desktop pop-session (due to pop-desktop) chrome-gnome-shell (due to pop-desktop) gdm3 (due to pop-desktop) gnome-shell (due to pop-desktop) pop-default-settings (due to pop-desktop)
0 upgraded, 1 newly installed, 28 to remove and 0 not upgraded.
Need to get 25.0 kB of archives.
After this operation, 25.2 MB disk space will be freed.
You are about to do something potentially harmful.
To continue type in the phrase 'Yes, do as I say!'
 ?]
```

**Comment by pipewire-debian** [comment] 2021-05-04 15:20
this is not a full log. how can i know which command you invoked with which arguments? PipeWire never depends on these packages you are showing. So needless to remove those packages. You can see my log, where I installed, remove, purging all PW related packages, Did I need to remove these packages? May be your whole system is broken already.

**Comment by pipewire-debian** [comment] 2021-05-04 15:51
can you check `libopenaptx*` is already installed by another package or not?    
output of `sudo dpkg --list | grep -i openaptx` and `apt policy libopenaptx0`?

**Comment by vranki** [comment] 2021-05-04 17:12
On Ubuntu 21.04 situation is this:

```bash
cos@trabant:~$ sudo dpkg --list | grep -i openaptx
cos@trabant:~$ apt policy libopenaptx0
libopenaptx0:
  Installed: (none)
  Candidate: 0.2.0-4
  Version table:
     0.2.0-4 500
        500 http://fi.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
cos@trabant:~$ sudo apt install libopenaptx0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libopenaptx0
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 14,0 kB of archives.
After this operation, 43,0 kB of additional disk space will be used.
Get:1 http://fi.archive.ubuntu.com/ubuntu groovy/universe amd64 libopenaptx0 amd64 0.2.0-4 [14,0 kB]
Fetched 14,0 kB in 0s (232 kB/s)          
Selecting previously unselected package libopenaptx0:amd64.
(Reading database ... 378942 files and directories currently installed.)
Preparing to unpack .../libopenaptx0_0.2.0-4_amd64.deb ...
Unpacking libopenaptx0:amd64 (0.2.0-4) ...
Setting up libopenaptx0:amd64 (0.2.0-4) ...
Processing triggers for libc-bin (2.32-0ubuntu3) ...
cos@trabant:~$ sudo apt install libspa-0.2-bluetooth
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libspa-0.2-bluetooth : Depends: libopenaptx0 (>= 0.2.0-5~) but 0.2.0-4 is to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by pipewire-debian** [comment] 2021-05-04 17:50
> The following packages have unmet dependencies:
>  libspa-0.2-bluetooth : Depends: libopenaptx0 (>= 0.2.0-5~) but 0.2.0-4 is to be installed
> E: Unable to correct problems, you have held broken packages.
> ```
@vranki
version of `libopenaptx0` on hirsute(21.04) is 0.2.0-5, check [here](https://packages.ubuntu.com/hirsute/libopenaptx0) thats mean you need to sync your repo. please do a `sudo apt-get update && sudo apt-get upgrade`. you can find `libopenaptx0=2.0-5` is going to be installed.  and finally `libspa-0.2-bluetooth` will be installed.

**Comment by vranki** [comment] 2021-05-04 19:27
Correct - looks like my system has packages messed up and it actually reports being 20.10 although I'm pretty sure I upgraded to 21.04. Thanks.

**Comment by souravdas142** [comment] 2021-05-04 19:51
I made available `libopenaptx0=2.0-7` for ubuntu 20.10 also, sync your repo again and upgrade.

**Comment by alsoGAMER** [comment] 2021-05-05 00:56
> this is not a full log. how can i know which command you invoked with which arguments? PipeWire never depends on these packages you are showing. So needless to remove those packages. You can see my log, where I installed, remove, purging all PW related packages, Did I need to remove these packages? May be your whole system is broken already.

Sorry, here's the command I invoked:
`sudo apt purge libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,bin,locales,tests}}`

**Comment by alsoGAMER** [comment] 2021-05-05 00:58
> can you check `libopenaptx*` is already installed by another package or not?
> output of `sudo dpkg --list | grep -i openaptx` and `apt policy libopenaptx0`?

```
sudo dpkg --list | grep -i openaptx                                                                                                                                                                                                     

ii  libopenaptx0:amd64                               0.2.0-7                                              amd64        Audio Processing Technology codec (aptX), shared libraries
```

```
apt policy libopenaptx0                                                                                                                                                                                                                

libopenaptx0:
  Installed: 0.2.0-7
  Candidate: 0.2.0-7
  Version table:
 *** 0.2.0-7 500
        500 http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.2.0-4 500
        500 http://it.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
```

**Comment by alsoGAMER** [comment] 2021-05-05 01:04
> > The following packages have unmet dependencies:
> > libspa-0.2-bluetooth : Depends: libopenaptx0 (>= 0.2.0-5~) but 0.2.0-4 is to be installed
> > E: Unable to correct problems, you have held broken packages.
> 
> @vranki
> version of `libopenaptx0` on hirsute(21.04) is 0.2.0-5, check [here](https://packages.ubuntu.com/hirsute/libopenaptx0) thats mean you need to sync your repo. please do a `sudo apt-get update && sudo apt-get upgrade`. you can find `libopenaptx0=2.0-5` is going to be installed. and finally `libspa-0.2-bluetooth` will be installed.

This worked for me.

**Comment by souravdas142** [comment] 2021-05-05 01:12
@alsoGAMER  If the problem is solved, Can I close the issue?

**Comment by alsoGAMER** [comment] 2021-05-05 01:14
> @alsoGAMER  If the problem is solved, Can I close the issue?

Yes, you can close it

**Comment by pipewire-debian** [comment] 2021-05-05 01:23
Mostly Repo was not synched or system was not upgraded to the latest version.

**Closed as completed by pipewire-debian** 2021-05-05 01:23 UTC
