### ISSUE TITLE
pipewire: symbol lookup error: pipewire: undefined symbol: PW_LOG_TOPIC_DEFAULT

### ISSUE THREAD

**Issue by alaborderie** [pipewire-debian/pipewire-debian#51] opened 2022-03-16 00:44 UTC
**If you Completed all troubleshoot options, check below**     
- [x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Desktop (please complete the following information):**
 - Distro: Pop!_OS
 - Desktop: Gnome
 - Version: 21.10
 - PipeWire Related packages Version: pipewire 0.3.48-1 pipewire-doc 0.3.48 blueman-git 2.2.4-1  wireplumber 0.4.8 wireplumber-doc 0.4.8
 - Kernel version: 5.16.11-76051611-generic

**Describe the bug**
After installing pipewire, following instructions on my system always ends up with services not starting.
pipewire -v returns  `pipewire: symbol lookup error: pipewire: undefined symbol: PW_LOG_TOPIC_DEFAULT`
pactl info returns 
```
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
```

**To Reproduce**
Follow instructions to install pipewire as a replacement of pulseaudio on Pop 21.10

**Expected behavior**
pipewire -v should at least print its own version

**Journal log and status of related services**
```
Mar 16 01:32:29 pop-os systemd[2898]: pipewire.service: Scheduled restart job, restart counter is at 5.
Mar 16 01:32:29 pop-os systemd[2898]: pipewire-pulse.service: Scheduled restart job, restart counter is at 5.
Mar 16 01:32:29 pop-os systemd[2898]: pipewire.service: Start request repeated too quickly.
Mar 16 01:32:29 pop-os systemd[2898]: pipewire.service: Failed with result 'exit-code'.
Mar 16 01:32:29 pop-os systemd[2898]: pipewire.socket: Failed with result 'service-start-limit-hit'.
Mar 16 01:32:29 pop-os systemd[2898]: pipewire-pulse.service: Start request repeated too quickly.
Mar 16 01:32:29 pop-os systemd[2898]: pipewire-pulse.service: Failed with result 'exit-code'.
Mar 16 01:32:29 pop-os systemd[2898]: pipewire-pulse.socket: Failed with result 'service-start-limit-hit'.
Mar 16 01:32:32 pop-os pipewire[59821]: /usr/bin/pipewire: symbol lookup error: /usr/bin/pipewire: undefined symbol: PW_LOG_TOPIC_DEFAULT
Mar 16 01:32:32 pop-os systemd[2898]: pipewire.service: Main process exited, code=exited, status=127/n/a
Mar 16 01:32:32 pop-os systemd[2898]: pipewire.service: Failed with result 'exit-code'.
Mar 16 01:32:32 pop-os systemd[2898]: pipewire.service: Scheduled restart job, restart counter is at 1.
Mar 16 01:32:32 pop-os pipewire[59890]: /usr/bin/pipewire: symbol lookup error: /usr/bin/pipewire: undefined symbol: PW_LOG_TOPIC_DEFAULT
Mar 16 01:32:32 pop-os systemd[2898]: pipewire.service: Main process exited, code=exited, status=127/n/a
Mar 16 01:32:32 pop-os systemd[2898]: pipewire.service: Failed with result 'exit-code'.
Mar 16 01:32:32 pop-os systemd[2898]: pipewire.service: Scheduled restart job, restart counter is at 2.
Mar 16 01:32:32 pop-os pipewire[59892]: /usr/bin/pipewire: symbol lookup error: /usr/bin/pipewire: undefined symbol: PW_LOG_TOPIC_DEFAULT
Mar 16 01:32:32 pop-os systemd[2898]: pipewire.service: Main process exited, code=exited, status=127/n/a
Mar 16 01:32:32 pop-os systemd[2898]: pipewire.service: Failed with result 'exit-code'.
Mar 16 01:32:32 pop-os systemd[2898]: pipewire.service: Scheduled restart job, restart counter is at 3.
Mar 16 01:32:32 pop-os pipewire[59894]: /usr/bin/pipewire: symbol lookup error: /usr/bin/pipewire: undefined symbol: PW_LOG_TOPIC_DEFAULT
Mar 16 01:32:32 pop-os systemd[2898]: pipewire.service: Main process exited, code=exited, status=127/n/a
Mar 16 01:32:32 pop-os systemd[2898]: pipewire.service: Failed with result 'exit-code'.
Mar 16 01:32:33 pop-os systemd[2898]: pipewire.service: Scheduled restart job, restart counter is at 4.
Mar 16 01:32:33 pop-os pipewire[59896]: /usr/bin/pipewire: symbol lookup error: /usr/bin/pipewire: undefined symbol: PW_LOG_TOPIC_DEFAULT
Mar 16 01:32:33 pop-os systemd[2898]: pipewire.service: Main process exited, code=exited, status=127/n/a
Mar 16 01:32:33 pop-os systemd[2898]: pipewire.service: Failed with result 'exit-code'.
Mar 16 01:32:33 pop-os systemd[2898]: pipewire.service: Scheduled restart job, restart counter is at 5.
Mar 16 01:32:33 pop-os systemd[2898]: pipewire.service: Start request repeated too quickly.
Mar 16 01:32:33 pop-os systemd[2898]: pipewire.service: Failed with result 'exit-code'.
Mar 16 01:32:33 pop-os systemd[2898]: pipewire.socket: Failed with result 'service-start-limit-hit'.
```

___

Hey! So I'm not sure about this issue, and I can't seem to get past this error.
I see PW_LOG_TOPIC_DEFAULT being mentioned in the source code, but not being sure what .symbols files are, I don't really know what to try to fix it... :/

**Comment by souravdas142** [comment] 2022-03-16 03:32
Hii @alaborderie  is https://github.com/pipewire-debian/pipewire-debian/blob/c5fc8cd0ce7d605a35d2972756b5d35185599d6f/pipewire/debian/libpipewire-0.3-0.symbols#L3 not the same ?

Did you missed some component to be installed ? I can't reproduce the issue here...

run this again...          
 ```bash
sudo apt install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,bin,locales,tests}}
```

And if you go through the [buildLog.log](https://launchpadlibrarian.net/589542597/buildlog_ubuntu-impish-amd64.pipewire_0.3.48.r23.g8673f8c-3~ubuntu21.10_BUILDING.txt.gz) you can't find any missing symbols to be written in `.symbol` file

**Comment by alaborderie** [comment] 2022-03-16 08:40
Hi @souravdas142,
Yes this is the symbol mentioned in the error, but I don't really know what it is.

Here is the output after trying to install : 
```
➜ sudo apt install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,bin,locales,tests}}
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gstreamer1.0-pipewire is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
libpipewire-0.3-0 is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
libpipewire-0.3-dev is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
libpipewire-0.3-modules is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
libspa-0.2-bluetooth is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
libspa-0.2-dev is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
libspa-0.2-jack is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
libspa-0.2-modules is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
pipewire is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
pipewire-audio-client-libraries is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
pipewire-bin is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
pipewire-locales is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
pipewire-pulse is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
pipewire-tests is already the newest version (0.3.48.r23.g8673f8c-3~ubuntu21.10).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
```

Do you know by chance what this symbols refers to?
Do I need an environment variable so pipewire can find it (like LD_LIBRARY_PATH for example)?
I might have a missing env var for some reason.
This is my LD_LIBRARY_PATH as I know this env var being empty caused me problems in the past:
```
➜ echo $LD_LIBRARY_PATH
/user/local/lib
```

**Comment by souravdas142** [comment] 2022-03-29 15:29
Sorry...
had no time to inspect this, As prior inspection it is not producing here.
Suggesting to open a question on askubuntu or stackoverflow or specific subreddit.

As the issue not related to PipeWire or the package itself So closing this. Reopen if someone encounter same. Thank you.

**Closed as completed by souravdas142** 2022-03-29 15:29 UTC
Labels: cannot reproduce

**Comment by alaborderie** [comment] 2022-03-29 15:44
It's fine, I myself gave up after hours and hours of trying.

I'm getting a new laptop soon and will try to reproduce on this one, because I noticed pipewire would also fail when building from source, or when using my distro repository.

Sorry for the inconvenience and thank your for trying.

**Comment by gegoxaren** [comment] 2022-10-03 16:41
@alaborderie: 
This could fix your issue.
https://github.com/pipewire-debian/pipewire-debian/issues/77#issuecomment-1265733581

**Comment by alaborderie** [comment] 2022-10-03 18:13
Hi @gegoxaren and thanks for the solution.

I ended up reinstalling my system to have a clean install of 22.04 a few months ago, and do not have the issue anymore
