### ISSUE TITLE
How to remove packages?

### ISSUE THREAD

**Issue by trappar** [pipewire-debian/pipewire-debian#14] opened 2021-06-03 10:58 UTC
I followed the instructions in the wiki, but then decided that I didn't want to stick with this solution. I've tried to remove the packages that I installed in the process, but it seems that some of them can't be removed (pipewire-bin for example) - gnome itself is dependent on them. Was this dependency added in the process of following the instructions? Or is it possible these packages were already installed?

Either way, documentation on how to revert the installation described in the wiki would be very helpful.

**Comment by souravdas142** [comment] 2021-06-03 15:13
see https://pastebin.com/FJGEjqPQ there is no gnome dependencies. Uninstall is quite straightforward like installation. Reverse of installation process.  

> Either way, documentation on how to revert the installation described in the wiki would be very helpful.

What to write man? Everything is simple. 

 The main goal of this PPA 
1. Make Everything simple as much as possible.
2. To provide the latest release of PipeWire to `debian/ubuntu` users without modifying anything as the version is very old on their official repository.
3. To help its developers to make the PipeWire a bugfree product. As the Majority of Linux users targets `ubuntu/debian` based distros, If they can test PipeWire and report bugs or feature request to upstream you are unknowingly contribute to the project.

**Comment by souravdas142** [comment] 2021-06-03 15:13
Meanwhile **PipeWire 0.3.29** is released you can try.

**Comment by trappar** [comment] 2021-06-03 22:05
Attempting to even remove just "pipewire" causes the following on my machine:

```bash
sudo apt remove pipewire                     
[sudo] password for trappar: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gir1.2-accountsservice-1.0 gir1.2-gck-1 gir1.2-gcr-3 gir1.2-gdm-1.0
  gir1.2-gnomebluetooth-1.0 gir1.2-graphene-1.0 gir1.2-mutter-7 gir1.2-nm-1.0
  gir1.2-nma-1.0 gir1.2-rsvg-2.0 gir1.2-upowerglib-1.0 gnome-session-bin
  gnome-session-common gnome-shell-common gnome-shell-extension-system76-power
  gnome-startup-applications gtk2-engines-murrine libfreerdp2-2 libmutter-7-0
  libvncserver1 libwinpr2-2 libxcb-res0 libxkbcommon-x11-0 mutter-common
  pop-gnome-shell-theme pop-gtk-theme pop-icon-theme pop-shell
  pop-shell-plugin-system76-power pop-shell-shortcuts pop-sound-theme
  pop-theme switcheroo-control xwayland
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  policykit-1-gnome
The following packages will be REMOVED:
  chrome-gnome-shell gdm3 gnome-remote-desktop gnome-shell
  gnome-shell-extension-alt-tab-raise-first-window
  gnome-shell-extension-always-show-workspaces
  gnome-shell-extension-appindicator gnome-shell-extension-desktop-icons-ng
  gnome-shell-extension-pop-shop-details gnome-shell-extension-prefs
  gstreamer1.0-pipewire pipewire pop-default-settings pop-desktop pop-session
The following NEW packages will be installed:
  policykit-1-gnome
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  pop-desktop pop-session (due to pop-desktop)
  chrome-gnome-shell (due to pop-desktop) gdm3 (due to pop-desktop)
  gnome-shell (due to pop-desktop) pop-default-settings (due to pop-desktop)
0 upgraded, 1 newly installed, 15 to remove and 0 not upgraded.
Need to get 25.0 kB of archives.
After this operation, 10.1 MB disk space will be freed.
You are about to do something potentially harmful.
To continue type in the phrase 'Yes, do as I say!'
```

This appears to be because...

```bash
sudo dpkg --remove pipewire
dpkg: dependency problems prevent removal of pipewire:amd64:
 gstreamer1.0-pipewire:amd64 depends on pipewire (= 0.3.28-1~ubuntu20.10).
 gnome-remote-desktop depends on pipewire (>= 0.3.0).

dpkg: error processing package pipewire:amd64 (--remove):
 dependency problems - not removing
Errors were encountered while processing:
 pipewire:amd64
```

**Comment by souravdas142** [comment] 2021-06-04 01:23
> gnome-remote-desktop depends on pipewire (>= 0.3.0).

Read above carefully. what can i do for then? And all dependencies of https://packages.ubuntu.com/hirsute/gnome-remote-desktop will be removed as well. This is general problem, you have to search on net. PipeWire doesn't have any dependencies on above you mentioned. **Please always use `issue template` for reporting, it saves my time**

**Comment by souravdas142** [comment] 2021-06-04 12:21
Hii @trappar  everything is fine with pipewire on my machine look below :

```bash
pop-os@pop-os:~$ pactl info
Server String: /run/user/999/pulse/native
Library Protocol Version: 34
Server Protocol Version: 35
Is Local: yes
Client Index: 57
Tile Size: 65472
User Name: pop-os
Host Name: pop-os
Server Name: PulseAudio (on PipeWire 0.3.29)
Server Version: 14.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_05.0.analog-stereo
Default Source: alsa_card.pci-0000:00:05.0.capture.0.0
Cookie: 51cc:9393
pop-os@pop-os:~$
```

**The problem is because of `PipeWire` is already install as `gnome-remote-desktop` depends on `pipewire (>= 0.3.0)` and there is no way to completely remove `PipeWire`. To insall latest version follow [wiki](https://github.com/pipewire-debian/pipewire-debian/wiki), If installation terminates with error run `sudo apt-get install --fix-broken`. This would make `PipeWire` install successfully. After that on every 15 days `PipeWire` should be upgraded as it is its release cycle.**

How ever If you still want to remove there are tons of tutorial available on the internet like this one : [`ppa-purge`](https://www.omgubuntu.co.uk/2019/12/how-to-remove-ppa-ubuntu) program, which will downgrade to system defaults package version.

These are edge case, I can't write every edge case in installation wiki. There are thousands of `debian` derivated os. So for which one I should write. 

> **How to remove Packages?**

Tons of this types of questions and answer are available on internet, Search it.


:warning:  **Can you confirm, Does it solves your problem? May I close it?**

**Comment by trappar** [comment] 2021-06-07 04:26
Yes, you can close this.

**Comment by pipewire-debian** [comment] 2021-06-07 04:40
Thank you, **Closing it now**., As you told me, I have included `uninstallation instructions` and included `ppa-purge` program naively in this PPA, see this https://pipewire-debian.github.io/pipewire-debian/#uninstalling. If you wish you can further install and test it.

**Closed as completed by pipewire-debian** 2021-06-07 04:40 UTC
Labels: invalid, blind install
