### ISSUE TITLE
Cannot install libldacbt-{abr,enc}2

### ISSUE THREAD

**Issue by mcarans** [pipewire-debian/pipewire-debian#10] opened 2021-05-17 01:48 UTC
**If you Completed all troubleshoot options, check below**     
- [ X]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [ X]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Describe the bug**
Unable to install dependent libraries

**To Reproduce**
sudo apt install libldacbt-{abr,enc}2

**Expected behavior**
Succesful install of libraries

**Screenshots**
```
Preparing to unpack .../libldacbt-enc2_2.0.2.3+git20200429+ed310a0-5_amd64.deb ...
Unpacking libldacbt-enc2:amd64 (2.0.2.3+git20200429+ed310a0-5) ...
dpkg: error processing archive /var/cache/apt/archives/libldacbt-enc2_2.0.2.3+git20200429+ed310a0-5_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libldacBT_enc.so.2', which is also in package libldac:amd64 2.0.2.3~r26478861
Preparing to unpack .../libldacbt-abr2_2.0.2.3+git20200429+ed310a0-5_amd64.deb ...
Unpacking libldacbt-abr2:amd64 (2.0.2.3+git20200429+ed310a0-5) ...
dpkg: error processing archive /var/cache/apt/archives/libldacbt-abr2_2.0.2.3+git20200429+ed310a0-5_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libldacBT_abr.so.2', which is also in package libldac:amd64 2.0.2.3~r26478861
Errors were encountered while processing:
 /var/cache/apt/archives/libldacbt-enc2_2.0.2.3+git20200429+ed310a0-5_amd64.deb
 /var/cache/apt/archives/libldacbt-abr2_2.0.2.3+git20200429+ed310a0-5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I tried ignoring the error and continuing, but got:
```
The following packages have unmet dependencies:
 libspa-0.2-bluetooth : Depends: libldacbt-abr2 (>= 2.0.2) but it is not going to be installed
                        Depends: libldacbt-enc2 (>= 2.0.2) but it is not going to be installed

```

**Desktop (please complete the following information):**
 - Distro: [e.g. Ubuntu] Linux Mint
 - Desktop Environment [e.g. Gnome] Cinnamon
 - Version [e.g. 20.04] 20.1

**Comment by pipewire-debian** [comment] 2021-05-17 02:28
@mcarans  duplicate of #8

**Closed as completed** 2021-05-17 02:43 UTC
Labels: duplicate
