### ISSUE TITLE
Keep debs of previous Pipewire versions in the PPA

### ISSUE THREAD

**Issue by codethief** [pipewire-debian/pipewire-debian#40] opened 2022-01-10 22:16 UTC
I would like to suggest to keep the most recent, say, ~5 Pipewire releases in the PPA, so that it's easy to roll back an update in case of regressions and new bugs. For instance, I just ran into https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1975 which seems to have been introduced with v0.3.41 or v0.3.42. Unfortunately, though, I can't downgrade back to v0.3.40 since I can't find the corresponding deb files anywhere (neither in the PPA nor anywhere else).

**Comment by souravdas142** [comment] 2022-01-23 13:13
duplicate of #32  Seems peoples have lots of problem finding old releases, I will mention it in [Readme.md](../Readme.md)

**Closed as completed** 2022-01-23 13:14 UTC

**Comment by codethief** [comment] 2022-01-24 17:05
Thanks so much! I had really tried everything, so I'm glad I wasn't the only one haha.

What could be the reason, though, that apt-get doesn't find those old releases?

**Comment by souravdas142** [comment] 2022-01-24 17:10
apt only find releases not superseeded one...

This behaviour is true for all distros... you need to manually download debs and install with `dpkg -i`
