### ISSUE TITLE
Wireplumber 0.4.10.r48.g37bd392-1~ubuntu22.04 (latest release) is broken

### ISSUE THREAD

**Issue by magnuslarsen** [pipewire-debian/pipewire-debian#68] opened 2022-06-30 17:29 UTC
**If you Completed all troubleshoot options, check below**     
- [x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Desktop (please complete the following information):**
 - Distro: [e.g. Ubuntu] Ubuntu
 - Desktop: Environment [e.g. Gnome] KDE
 - Version: [e.g. 20.04] 22.04
 - PipeWire Related packages Version: [pipewire, wireplumber, libcamera, etc.] pipewire=0.3.53-1\~ubuntu22.04 wireplumber=0.4.10.r48.g37bd392-1\~ubuntu22.04
 - Kernel version: 5.15.0-40-generic

**Describe the bug**
Latest wireplumber build seems broken, [please see my thread from upstream wireplumber](https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/297#note_1450534)

**To Reproduce**
Steps to reproduce the behavior: install the latest version (from a couple of hours ago), and run it. It breaks instantly with a floating point exception

As you don't have multiple versions on the PPA (or so it seems), I can't check if it is the version diff :-)

**Expected behavior**
Not to break

**Screenshots**
(snapshot of PW related services or anything)

Please see the thread above

**Journal log and status of related services**

Please see the thread above

**Additonal Information (If applicable):**                                          
.                                          
.                                          
.

**Comment by souravdas142** [comment] 2022-06-30 18:10
Sorry for the issue. Till the issue is fixed you can use previous version from https://launchpad.net/~pipewire-debian/+archive/ubuntu/wireplumber-upstream/+packages?field.name_filter=wireplumber&field.status_filter=&field.series_filter=

you need to manually download all `*.deb` files  and install, before dont forget to remove current version of wireplumber.

**Comment by laurentdebricon** [comment] 2022-06-30 21:35
confirming the regression

**Comment by souravdas142** [comment] 2022-07-01 02:52
see this https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/288
assuming he is not using this PPA but still have same issue.

**Comment by souravdas142** [comment] 2022-07-01 06:58
Hi @laurentdebricon  @magnuslarsen 

Please see: https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/297#note_1451189

We have bisected the bad commit which introduced the problem. We will be released a new version soon after fixing the issue. 
Thank you.

**Comment by magnuslarsen** [comment] 2022-07-01 07:17
No, thank you!

**Comment by souravdas142** [comment] 2022-07-02 03:36
Sorry Everyone, The cause was for libcamera, I had't update to the release date of pipewire to allign. see backtrace below. problem is fixed now. Thank you. And again sorry for the inconvenience and your support.
[backtrace.log](https://github.com/pipewire-debian/pipewire-debian/files/9032353/backtrace.log)

**Comment by souravdas142** [comment] 2022-07-02 04:16
As we discussed on upstream we will split `pipewire` package (more specifically `libspa-0.2-modules`) into `libspa-0.2-libcamera` If anybody wants to use that they can otherwise they shouldn't install `libspa-0.2-libcamera`.

**Comment by Pharmasolin** [comment] 2022-07-05 21:40
In case someone is checking this issue to see if the issue is fixed in PPA and it can be enabled again - it is fixed.

**Comment by thuandt** [comment] 2022-07-06 01:34
problem is fixed in new build <3

**Comment by souravdas142** [comment] 2022-07-06 10:53
Thank you. Closing now.

**Closed as completed by souravdas142** 2022-07-06 10:53 UTC
