### ISSUE TITLE
Package failed to install. Error whilst installing package: trying to overwite 'usr/lib/x86_64-linux-gnu/libdacbt_enc.so.2', which is also in the package libldac

### ISSUE THREAD

**Issue by TheBlogHouse** [pipewire-debian/pipewire-debian#8] opened 2021-05-10 14:21 UTC
Thanks for creating this.

I have managed to get it working but hitting the following issues when trying to update my Ubuntu based system now:

_"Package failed to install. Error whilst installing package: trying to overwrite 'usr/lib/x86_64-linux-gnu/libdacbt_enc.so.2', which is also in the package libldac"_ That's via the 2.0.2.3+git20200429+ed310a0-4 that your repo has added and also the same for ibdacbt-abr2 ?

**Comment by souravdas142** [comment] 2021-05-10 15:52
**You should  create an issue always with `issue template`. It make easy to understand. Please Answer  👇 this**

**If you Completed all troubleshoot options, check below**     
- [ ]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [ ]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:


**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
(snapshot of PW related services or anything)

**Desktop (please complete the following information):**
 - Distro: [e.g. Ubuntu]
 - Desktop Environment [e.g. Gnome]
 - Version [e.g. 20.04]


**Journal log and status of related services**
Add any other context about the problem here.

**Comment by souravdas142** [comment] 2021-05-10 15:55
do you have any `libldac` preinstalled on your system? `dpkg --list | grep libldac` output?

**Comment by TheBlogHouse** [comment] 2021-05-10 18:23
Hi 

Sorry was only testing earlier and didn't have time to add much detail:

Kubuntu 21.04
KDE Plasma 5.21.4

I had AAC and aptX working well via Pulse Audio before 21.04 via https://launchpad.net/~berglh/+archive/ubuntu/pulseaudio-a2dp/+packages but as that isn't updated (yet?) thought I would try and move across to this when I saw your work.

```
sudo dpkg --list | grep libldac
ii  libldac:amd64                                 2.0.2.3~r26719261                                                    amd64        AOSP libldac dispatcher

```

If I try sudo apt-get upgrade I get...

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies.
 libspa-0.2-bluetooth : Depends: libldacbt-abr2 (>= 2.0.2) but it is not installed
                        Depends: libldacbt-enc2 (>= 2.0.2) but it is not installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

```
If I then try ~$ sudo apt --fix-broken install I get...


```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  libfaudio0 libpcre3:i386 libstb0 libvkd3d1 wine-stable-amd64
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libldacbt-abr2 libldacbt-enc2
The following NEW packages will be installed
  libldacbt-abr2 libldacbt-enc2
0 to upgrade, 2 to newly install, 0 to remove and 0 not to upgrade.
15 not fully installed or removed.
Need to get 0 B/29.2 kB of archives.
After this operation, 98.3 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 472170 files and directories currently installed.)
Preparing to unpack .../libldacbt-enc2_2.0.2.3+git20200429+ed310a0-4_amd64.deb ...
Unpacking libldacbt-enc2:amd64 (2.0.2.3+git20200429+ed310a0-4) ...
dpkg: error processing archive /var/cache/apt/archives/libldacbt-enc2_2.0.2.3+git20200429+ed310a0-4_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libldacBT_enc.so.2', which is also in package libldac:amd64 2.0.2.3~r26719261
Preparing to unpack .../libldacbt-abr2_2.0.2.3+git20200429+ed310a0-4_amd64.deb ...
Unpacking libldacbt-abr2:amd64 (2.0.2.3+git20200429+ed310a0-4) ...
dpkg: error processing archive /var/cache/apt/archives/libldacbt-abr2_2.0.2.3+git20200429+ed310a0-4_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libldacBT_abr.so.2', which is also in package libldac:amd64 2.0.2.3~r26719261
Errors were encountered while processing:
 /var/cache/apt/archives/libldacbt-enc2_2.0.2.3+git20200429+ed310a0-4_amd64.deb
 /var/cache/apt/archives/libldacbt-abr2_2.0.2.3+git20200429+ed310a0-4_amd64.deb
libdvd-pkg: Checking orig.tar integrity...
/usr/src/libdvd-pkg/libdvdcss_1.4.2.orig.tar.bz2: OK
libdvd-pkg: `apt-get check` failed, you may have broken packages. Aborting...
E: Sub-process /usr/bin/dpkg returned an error code (1)

```
I hope the above is helpful helping you help not only myself but others trying to move over using your PPA.

**Comment by souravdas142** [comment] 2021-05-10 18:45
This `libldac`  is not installing from my PPA, since ubuntu 21.04 officially includes this package, I removed this from PPA. 

So completely remove and purge any previous `libldac`  installed on your machine and try again.

**Comment by TheBlogHouse** [comment] 2021-05-10 18:56
Ok great - thanks for confirming that libldac isn't installed via your PPA however I still can't get get the libldac to remove coming from Pulse audio...

```
sudo apt remove pulseaudio-modules-bt libldac                 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package pulseaudio-modules-bt
:~$ sudo apt remove libldac                      
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies.
 libspa-0.2-bluetooth : Depends: libldacbt-abr2 (>= 2.0.2) but it is not going to be installed
                        Depends: libldacbt-enc2 (>= 2.0.2) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  libfaudio0 libpcre3:i386 libstb0 libvkd3d1 wine-stable-amd64
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libldacbt-abr2 libldacbt-enc2
The following NEW packages will be installed
  libldacbt-abr2 libldacbt-enc2
0 to upgrade, 2 to newly install, 0 to remove and 0 not to upgrade.
15 not fully installed or removed.
Need to get 0 B/29.2 kB of archives.
After this operation, 98.3 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 472170 files and directories currently installed.)
Preparing to unpack .../libldacbt-enc2_2.0.2.3+git20200429+ed310a0-4_amd64.deb ...
Unpacking libldacbt-enc2:amd64 (2.0.2.3+git20200429+ed310a0-4) ...
dpkg: error processing archive /var/cache/apt/archives/libldacbt-enc2_2.0.2.3+git20200429+ed310a0-4_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libldacBT_enc.so.2', which is also in package libldac:amd64 2.0.2.3~r26719261
Preparing to unpack .../libldacbt-abr2_2.0.2.3+git20200429+ed310a0-4_amd64.deb ...
Unpacking libldacbt-abr2:amd64 (2.0.2.3+git20200429+ed310a0-4) ...
dpkg: error processing archive /var/cache/apt/archives/libldacbt-abr2_2.0.2.3+git20200429+ed310a0-4_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libldacBT_abr.so.2', which is also in package libldac:amd64 2.0.2.3~r26719261
Errors were encountered while processing:
 /var/cache/apt/archives/libldacbt-enc2_2.0.2.3+git20200429+ed310a0-4_amd64.deb
 /var/cache/apt/archives/libldacbt-abr2_2.0.2.3+git20200429+ed310a0-4_amd64.deb
libdvd-pkg: Checking orig.tar integrity...
/usr/src/libdvd-pkg/libdvdcss_1.4.2.orig.tar.bz2: OK
libdvd-pkg: `apt-get check` failed, you may have broken packages. Aborting...
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by souravdas142** [comment] 2021-05-10 19:21
allow `libspa-0.2-bluetooth` also to be removed with `libldac` 
`sudo apt-get remove --purge libldac* libspa-0.2-bluetooth`

if you still have problem,  follow this  [askubuntu](https://askubuntu.com/a/490677) answer. then reinstall `libspa-0.2-bluetooth` with `sudo apt-get install --reinstall libspa-0.2-bluetooth` this will fetch all dependencies.

**Comment by TheBlogHouse** [comment] 2021-05-10 19:26
Thanks so much - those last steps seem to have fixed everything for me now.

If you would like me to test anything my end let me know but if not thanks for creating this PPA and your time helping here.

**Comment by souravdas142** [comment] 2021-05-10 19:36
would you like to test `blueman-git` from this ppa?   its optimized alot for pipewire. if you really want to install first read the [README.md this section](https://github.com/pipewire-debian/pipewire-debian#2-install-pipewire-or-blueman-git) carefully.

**Comment by TheBlogHouse** [comment] 2021-05-10 19:46
I don't really have a need for blueman as Kubuntu and KDE Plasma seems to give me all I need unless I'm missing something?

**Comment by souravdas142** [comment] 2021-05-10 20:01
Actually I never use kde, So I dont know. May be you better stay with default then. currently I am not using any DE, my main machine have Arch+i3 installed. The whole Ubuntu/debian family doesn't have a latest version of PipeWire, Thats why i created this. In recent days many peoples uses ubuntu/debian based distro,  If i avail them PW, then the more users can test it, Thats good for its devops to debug.

**Comment by TheBlogHouse** [comment] 2021-05-10 20:16
Yes I will stay with default KDE Plasma for now as it already lets me pick the codec I want to use for my Bluetooth headphones. Your PPA for Pipewire is certainly much appreciated by me as like I said I was awaiting a new Pulse audio workaround for AAC and aptX codecs but Pipewire seems work well and be more future focussed. Thanks again

**Comment by souravdas142** [comment] 2021-05-10 20:21
can you confirm one more thing? does your bt headset shows battery information with PW or PA?

**Comment by TheBlogHouse** [comment] 2021-05-11 08:30
No my bluetooth headset doesn't show battery information using PW in Kubuntu 21.04 but it didn't in 20.10 either using PA.

I have to say though testing the Bluetooth headphones this morning on various sound sources with either AAC or SBC using PW the audio keeps going distorted or choppy when I had no issues even on 21.04 using PA and SBC so is there anything I can check to try and stop this as this is a major downgrade?

EDIT - I have updated an issue over at https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1144 and referenced your PPA so hopefully there's some way I can get back to where I was with these headphones on PA.

**Comment by pipewire-debian** [comment] 2021-05-11 13:51
`libldacacbt-*` conflicts with another forign package. Since the issue is fixed, I am closing it now, further issue is being tracked by [upstream](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1144).

**Closed as completed by pipewire-debian** 2021-05-11 13:51 UTC
