### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mradeschnig** [pipewire-debian/pipewire-debian#13] opened 2021-05-19 15:52 UTC
**If you Completed all troubleshoot options, check below**     
- [x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [ x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Describe the bug**
I get errors when I issue this command.
servus@smallnode$ sudo apt install libfdk-aac2 libldacbt-{abr,enc}2 libopenaptx0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  libfdk-aac2 libldacbt-abr2 libldacbt-enc2 libopenaptx0
0 upgraded, 4 newly installed, 0 to remove and 7 not upgraded.
Need to get 660 kB of archives.
After this operation, 1.468 kB of additional disk space will be used.
Get:1 http://at.archive.ubuntu.com/ubuntu hirsute/multiverse amd64 libfdk-aac2 amd64 2.0.1-1 [617 kB]
Get:2 http://at.archive.ubuntu.com/ubuntu hirsute/universe amd64 libldacbt-enc2 amd64 2.0.2.3+git20200429+ed310a0-4 [24,6 kB]
Get:3 http://at.archive.ubuntu.com/ubuntu hirsute/universe amd64 libldacbt-abr2 amd64 2.0.2.3+git20200429+ed310a0-4 [4.644 B]
Get:4 http://at.archive.ubuntu.com/ubuntu hirsute/universe amd64 libopenaptx0 amd64 0.2.0-5 [14,2 kB]
Fetched 660 kB in 0s (2.033 kB/s)  
Selecting previously unselected package libfdk-aac2:amd64.
(Reading database ... 326920 files and directories currently installed.)
Preparing to unpack .../libfdk-aac2_2.0.1-1_amd64.deb ...
Unpacking libfdk-aac2:amd64 (2.0.1-1) ...
Preparing to unpack .../libldacbt-enc2_2.0.2.3+git20200429+ed310a0-4_amd64.deb .
..
Unpacking libldacbt-enc2:amd64 (2.0.2.3+git20200429+ed310a0-4) ...
dpkg: error processing archive /var/cache/apt/archives/libldacbt-enc2_2.0.2.3+gi
t20200429+ed310a0-4_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libldacBT_enc.so.2', which is al
so in package libldac:amd64 2.0.2.3~r26478861
Preparing to unpack .../libldacbt-abr2_2.0.2.3+git20200429+ed310a0-4_amd64.deb .
..
Unpacking libldacbt-abr2:amd64 (2.0.2.3+git20200429+ed310a0-4) ...
dpkg: error processing archive /var/cache/apt/archives/libldacbt-abr2_2.0.2.3+gi
t20200429+ed310a0-4_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libldacBT_abr.so.2', which is al
so in package libldac:amd64 2.0.2.3~r26478861
Selecting previously unselected package libopenaptx0:amd64.
Preparing to unpack .../libopenaptx0_0.2.0-5_amd64.deb ...
Unpacking libopenaptx0:amd64 (0.2.0-5) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libldacbt-enc2_2.0.2.3+git20200429+ed310a0-4_amd64.deb
 /var/cache/apt/archives/libldacbt-abr2_2.0.2.3+git20200429+ed310a0-4_amd64.deb
servus@smallnode:~$ sudo apt remove libfdk-aac2 libldacbt-{abr,enc}2 libopenaptx0

**Expected behavior**
installation without errors

**Desktop (please complete the following information):**
 - Distro: Ubuntu
 - Desktop Environment Gnome
 - Version 21.04

**Comment by souravdas142** [comment] 2021-05-19 15:58
duplicate of #8 btw wait 30 mins. pipewire 0.3.28 launched. debpackages are built but not published yet.

**Comment by souravdas142** [comment] 2021-05-19 19:31
Now you can insall 0.3.28 is released.

**Comment by pipewire-debian** [comment] 2021-05-22 12:53
As OP did not respond & may he solved the problem as it was duplicate of #8 already answered, I am closing it now.

**Closed as completed by pipewire-debian** 2021-05-22 12:53 UTC
Labels: duplicate, info needed, solved
